name: "NASA Rocket Science"
description: ""

url: "http://nasa-rocket-science.github.io"
#url: "http://localhost:4000/"

#paginate: 5
#paginate_path: "blog/page:num"
timezone: "America/New_York"

exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]

markdown: rdiscount
permalink: pretty
relative_permalinks: true

highlighter: pygments

# Custom vars
#current_version:  1.0
#repo:             https://github.com/sunpy/sunpy
#install_instructions: http://docs.sunpy.org/en/stable/guide/installation/